list: $/pensoft/knowledgelibrary/models/project/columns.yaml
modelClass: Pensoft\Knowledgelibrary\Models\Project
title: Projects
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/knowledgelibrary/projects/update/:id'
